# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainfood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainbit',
            name='description',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='brainbit',
            name='duration',
            field=models.DurationField(default='5:0'),
        ),
        migrations.AlterField(
            model_name='brainbit',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
