# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainfood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=64)),
                ('brain_bits', models.ManyToManyField(to='brainfood.BrainBit')),
            ],
        ),
    ]
