# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainfood', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainbit',
            name='description',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brainbit',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brainbit',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
