# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainfood', '0002_auto_20160409_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
