# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainfood', '0004_auto_20160409_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brainbit',
            old_name='brain_bits',
            new_name='tags',
        ),
    ]
