# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 00:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('brainfood', '0004_auto_20160409_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='brainbit',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 10, 0, 8, 44, 850048, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
