# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainfood', '0005_brainbit_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainbit',
            name='tags',
            field=models.ManyToManyField(blank=True, to='brainfood.Tag'),
        ),
    ]
