# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='canonisation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='reminiscence',
            field=models.DateField(blank=True, null=True),
        ),
    ]
