# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrons', '0002_auto_20160409_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='patron',
            name='prayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patrons.Prayer'),
        ),
    ]
