# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrons', '0003_auto_20160409_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
